# Use a lightweight Python image as the base
FROM python:3.8-slim

# Set the working directory inside the container
WORKDIR /app

# Copy everything from your current folder into /app in the container
COPY . .

# Run the main Python file when the container starts
CMD ["python", "Main.py"]
